### PR TITLE
Ignore backends that have no upstream servers

### PR DESCRIPTION
**Pull request by jakolehm**

### CODE REVIEW

**Comment by nevalla** [comment]
LGTM

**Comment by hans-d** [comment]
might introduce some issues when the ACL is present, but the used backend is not ...

**Comment by jakolehm** [comment]
@hans-d this should fix exactly that kind of issues... it does not write acl or backend it there are no upstream servers

**Comment by hans-d** [comment]
sorry, misread some of the changes. You can strike my remark ( @jakolehm you were just a bit too quick with your reply :-) )

**Pull request merged**
